-- File Name: we.sql
-- Purpose: Dameng Session wait and SQL overview
-- Created: 20260418  by  huangtingzhong

SELECT
    CAST(s.SESS_ID AS VARCHAR(20)) AS SID,
    SUBSTR(s.STATE, 1, 30) AS EVENT,
    s.USER_NAME AS USERNAME,
    SUBSTR(s.SQL_ID, 1, 18) AS SQL_ID,
    CASE
        WHEN s.EXEC_TIME < 1000 THEN CAST(s.EXEC_TIME AS VARCHAR(10)) || 'MS'
        WHEN s.EXEC_TIME < 1000000 THEN CAST(ROUND(s.EXEC_TIME / 1000.0, 2) AS VARCHAR(10)) || 'S'
        ELSE CAST(ROUND(s.EXEC_TIME / 1000000.0, 2) AS VARCHAR(10)) || 'KS'
    END AS EXEC_TIME,
    SUBSTR(s.APPNAME, 1, 30) AS PROGRAM,
    SUBSTR(s.CLNT_IP, 1, 20) AS CLIENT
FROM V$SESSIONS s
WHERE s.STATE <> 'IDLE'
  AND s.TYPE <> 'SYSTEM'
ORDER BY s.EXEC_TIME DESC;

-- Sessions with same SQL_ID (potential contention)
SELECT
    SQL_ID,
    STATE AS WAIT_EVENT,
    COUNT(*) AS HCOUNT
FROM V$SESSIONS
WHERE STATE <> 'IDLE'
  AND TYPE <> 'SYSTEM'
  AND SQL_ID IS NOT NULL
GROUP BY SQL_ID, STATE
HAVING COUNT(*) > 1
ORDER BY HCOUNT DESC;
